
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 19 14:50:23 BRT 2026
//----------------------------------------------------

package ExemploCup.lexicoExe3;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Sep 19 14:50:23 BRT 2026
  */
public class ParserSemantico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserSemantico() {super();}

  /** Constructor which sets the default scanner. */
  public ParserSemantico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserSemantico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\007\000\002\002\004\000\002\002\004\000\002\003" +
    "\003\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\004\011\006\001\002\000\004\002\020\001" +
    "\002\000\014\004\010\005\007\006\012\007\011\010\013" +
    "\001\002\000\014\004\uffff\005\uffff\006\uffff\007\uffff\010" +
    "\uffff\001\002\000\004\011\006\001\002\000\004\002\000" +
    "\001\002\000\004\011\006\001\002\000\004\011\006\001" +
    "\002\000\004\011\006\001\002\000\014\004\ufffb\005\ufffb" +
    "\006\ufffb\007\ufffb\010\ufffb\001\002\000\014\004\ufffd\005" +
    "\ufffd\006\ufffd\007\011\010\013\001\002\000\014\004\ufffc" +
    "\005\ufffc\006\ufffc\007\ufffc\010\ufffc\001\002\000\014\004" +
    "\ufffe\005\ufffe\006\ufffe\007\011\010\013\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\016" +
    "\001\001\000\002\001\001\000\004\003\015\001\001\000" +
    "\004\003\014\001\001\000\004\003\013\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserSemantico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserSemantico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserSemantico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserSemantico$actions {
  private final ParserSemantico parser;

  /** Constructor */
  CUP$ParserSemantico$actions(ParserSemantico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserSemantico$do_action(
    int                        CUP$ParserSemantico$act_num,
    java_cup.runtime.lr_parser CUP$ParserSemantico$parser,
    java.util.Stack            CUP$ParserSemantico$stack,
    int                        CUP$ParserSemantico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserSemantico$result;

      /* select the action based on the action number */
      switch (CUP$ParserSemantico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= expr DIV expr 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.peek()).value;
		 RESULT = e1 / e2; 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= expr MULT expr 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.peek()).value;
		 RESULT = e1 * e2; 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= expr MENOS expr 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.peek()).value;
		 RESULT = e1 - e2; 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= expr MAIS expr 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).right;
		Integer e2 = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.peek()).value;
		 RESULT = e1 + e2; 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr ::= INTEIRO 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.peek()).value;
		 RESULT = n; 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // expr_ptv ::= expr PTVIRG 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).value;
		 System.out.println("Resultado da expressao: " + e); 
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("expr_ptv",0, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          return CUP$ParserSemantico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= expr_ptv EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)).value;
		RESULT = start_val;
              CUP$ParserSemantico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.elementAt(CUP$ParserSemantico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSemantico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserSemantico$parser.done_parsing();
          return CUP$ParserSemantico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

