
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 19 14:50:23 BRT 2026
//----------------------------------------------------

package ExemploCup.lexicoExe3;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int MULT = 5;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int DIV = 6;
  public static final int EOF = 0;
  public static final int INTEIRO = 7;
}

