package unidade2;

public enum TokenExe2 {
    CHAVES,
    PARENTESES,
    PALAVRA_RESERVADA,
    TIPO_DE_VARIAVEL,
    RETORNO_DE_FUNCAO,
    ATRIBUICAO,
    IDENTIFICADOR,
    CONSTANTE,
    INTEIRO,
    DECIMAL,
    OPERADORARITMETICO,
    OPERADORCOMPARATIVO,
    OPERADORLOGICO,
    SIMBOLOESPECIAL,
    BRANCO,
    ERROR;
}
