
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 19 13:21:48 BRT 2026
//----------------------------------------------------

package ExemploCup.exe2;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Sep 19 13:21:48 BRT 2026
  */
public class ParserSintatico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserSintatico() {super();}

  /** Constructor which sets the default scanner. */
  public ParserSintatico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserSintatico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\022\000\002\002\004\000\002\002\011\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\007\000\002\004\011\000\002\004\003\000" +
    "\002\012\005\000\002\005\005\000\002\006\003\000\002" +
    "\006\003\000\002\007\006\000\002\011\005\000\002\010" +
    "\005\000\002\010\003\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\051\000\004\004\005\001\002\000\004\002\053\001" +
    "\002\000\004\005\006\001\002\000\004\012\007\001\002" +
    "\000\004\013\010\001\002\000\004\014\011\001\002\000" +
    "\014\006\020\007\023\010\022\014\013\023\024\001\002" +
    "\000\020\006\ufffd\007\ufffd\010\ufffd\011\ufffd\014\ufffd\015" +
    "\ufffd\023\ufffd\001\002\000\014\006\020\007\023\010\022" +
    "\014\013\023\024\001\002\000\020\006\ufff9\007\ufff9\010" +
    "\ufff9\011\ufff9\014\ufff9\015\ufff9\023\ufff9\001\002\000\016" +
    "\006\ufffe\007\ufffe\010\ufffe\014\ufffe\015\ufffe\023\ufffe\001" +
    "\002\000\020\006\ufffc\007\ufffc\010\ufffc\011\ufffc\014\ufffc" +
    "\015\ufffc\023\ufffc\001\002\000\004\023\047\001\002\000" +
    "\004\023\ufff6\001\002\000\016\006\020\007\023\010\022" +
    "\014\013\015\046\023\024\001\002\000\004\012\034\001" +
    "\002\000\004\023\ufff5\001\002\000\004\017\025\001\002" +
    "\000\006\022\030\023\026\001\002\000\012\013\ufff1\016" +
    "\ufff1\020\ufff1\021\ufff1\001\002\000\006\016\032\021\031" +
    "\001\002\000\012\013\ufff0\016\ufff0\020\ufff0\021\ufff0\001" +
    "\002\000\006\022\030\023\026\001\002\000\020\006\ufff4" +
    "\007\ufff4\010\ufff4\011\ufff4\014\ufff4\015\ufff4\023\ufff4\001" +
    "\002\000\012\013\ufff2\016\ufff2\020\ufff2\021\ufff2\001\002" +
    "\000\006\022\030\023\026\001\002\000\006\020\043\021" +
    "\031\001\002\000\004\013\037\001\002\000\014\006\020" +
    "\007\023\010\022\014\013\023\024\001\002\000\020\006" +
    "\ufffb\007\ufffb\010\ufffb\011\041\014\ufffb\015\ufffb\023\ufffb" +
    "\001\002\000\014\006\020\007\023\010\022\014\013\023" +
    "\024\001\002\000\020\006\ufffa\007\ufffa\010\ufffa\011\ufffa" +
    "\014\ufffa\015\ufffa\023\ufffa\001\002\000\006\022\030\023" +
    "\026\001\002\000\006\013\ufff3\021\031\001\002\000\016" +
    "\006\uffff\007\uffff\010\uffff\014\uffff\015\uffff\023\uffff\001" +
    "\002\000\004\002\000\001\002\000\004\016\050\001\002" +
    "\000\020\006\ufff7\007\ufff7\010\ufff7\011\ufff7\014\ufff7\015" +
    "\ufff7\023\ufff7\001\002\000\016\006\020\007\023\010\022" +
    "\014\013\015\052\023\024\001\002\000\020\006\ufff8\007" +
    "\ufff8\010\ufff8\011\ufff8\014\ufff8\015\ufff8\023\ufff8\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\051\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\003\020\004\014\005\011\006\016\007" +
    "\015\012\013\001\001\000\002\001\001\000\016\003\050" +
    "\004\014\005\011\006\016\007\015\012\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\044\005\011\006" +
    "\016\007\015\012\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\026\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\010\034\011\035\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\004\037\005\011\006\016\007\015\012" +
    "\013\001\001\000\002\001\001\000\014\004\041\005\011" +
    "\006\016\007\015\012\013\001\001\000\002\001\001\000" +
    "\004\010\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\004\044\005\011\006\016\007\015\012\013\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserSintatico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserSintatico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserSintatico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        System.out.println("AVISO - " + message);
    }

    public void report_fatal_error(String message, Object info) {
        System.out.println("ERRO - " + message);
        System.exit(-1);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserSintatico$actions {
  private final ParserSintatico parser;

  /** Constructor */
  CUP$ParserSintatico$actions(ParserSintatico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserSintatico$do_action(
    int                        CUP$ParserSintatico$act_num,
    java_cup.runtime.lr_parser CUP$ParserSintatico$parser,
    java.util.Stack            CUP$ParserSintatico$stack,
    int                        CUP$ParserSintatico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserSintatico$result;

      /* select the action based on the action number */
      switch (CUP$ParserSintatico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= INTEIRO 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= VARIAVEL 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= expr MULT expr 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr_rel ::= expr MAIOR expr 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("expr_rel",7, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // atrib ::= VARIAVEL ATRIB expr PTVG 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("atrib",5, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-3)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_dado ::= TIPO_FLOAT 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("tipo_dado",4, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_dado ::= TIPO_INTEIRO 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("tipo_dado",4, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // decl_var ::= tipo_dado VARIAVEL PTVG 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bloco ::= CHAVE_ESQUERDA lista_comandos CHAVE_DIREITA 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("bloco",8, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // comando ::= bloco 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("comando",2, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // comando ::= IF PARENTESE_ESQUERDO expr_rel PARENTESE_DIREITO comando ELSE comando 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("comando",2, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-6)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // comando ::= IF PARENTESE_ESQUERDO expr_rel PARENTESE_DIREITO comando 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("comando",2, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-4)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // comando ::= atrib 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("comando",2, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // comando ::= decl_var 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("comando",2, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_comandos ::= comando 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("lista_comandos",1, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_comandos ::= lista_comandos comando 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("lista_comandos",1, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= VOID MAIN PARENTESE_ESQUERDO PARENTESE_DIREITO CHAVE_ESQUERDA lista_comandos CHAVE_DIREITA 
            {
              Object RESULT =null;

              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-6)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          return CUP$ParserSintatico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-1)).value;
		RESULT = start_val;
              CUP$ParserSintatico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.elementAt(CUP$ParserSintatico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSintatico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserSintatico$parser.done_parsing();
          return CUP$ParserSintatico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

