
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 19 13:21:48 BRT 2026
//----------------------------------------------------

package ExemploCup.exe2;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ELSE = 7;
  public static final int PTVG = 12;
  public static final int IF = 6;
  public static final int ATRIB = 13;
  public static final int INTEIRO = 16;
  public static final int PARENTESE_ESQUERDO = 8;
  public static final int FLOAT = 18;
  public static final int EOF = 0;
  public static final int MULT = 15;
  public static final int MAIN = 3;
  public static final int CHAVE_ESQUERDA = 10;
  public static final int error = 1;
  public static final int MAIOR = 14;
  public static final int PARENTESE_DIREITO = 9;
  public static final int VARIAVEL = 17;
  public static final int VOID = 2;
  public static final int CHAVE_DIREITA = 11;
  public static final int TIPO_FLOAT = 5;
  public static final int TIPO_INTEIRO = 4;
}

